### ISSUE TITLE
小米平板5无法使用竖屏时上下分屏

### ISSUE THREAD

**Issue by DhG314** [YifePlayte/MaxMiPadInput#19]
小米平板5, 系统是hyperos1.0.3.0(android13)
只打开了竖屏时上下分屏这个选项, 现象和[isuue#11](https://github.com/YifePlayte/MaxMiPad/issues/11)一样

**Comment by DhG314** [comment]
可能有用的log

[ 2024-11-08T23:16:35.553    10124:  2457:  2457 I/LSPosed-Bridge  ] [I/MaxMiPad] Inited package: Home
[ 2024-11-08T23:16:35.573    10124:  2457:  2457 I/LSPosed-Bridge  ] [I/MaxMiPad] Inited hook: VerticalSplitOnPortrait in: com.miui.home
[ 2024-11-08T23:16:35.870     1000:  3024:  3024 I/LSPosed-Bridge  ] [E/MaxMiPad] Failed init hook: VerticalSplitOnPortrait in: com.android.systemui: java.lang.ClassNotFoundException: com.android.wm.shell.common.split.SplitUtilsImpl
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at cn.fkj233.ui.activity.e.q(Unknown Source:5)
	at com.yifeplayte.maxmipadinput.hook.hooks.multiple.VerticalSplitOnPortrait$hooks$1.b(Unknown Source:64)
	at o.b.c(Unknown Source:32)
	at com.yifeplayte.maxmipadinput.hook.MainHook.handleLoadPackage(Unknown Source:112)
	at Diw.RRSVElx.ZVBFqlA.Cb.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at Diw.RRSVElx.ZVBFqlA.Cb.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at Diw.RRSVElx.ZVBFqlA.Cb.callbacks.XCallback.callAll(Unknown Source:26)
	at g0.a(Unknown Source:281)
	at java.lang.reflect.Method.invoke(Native Method)
	at J.callback(Unknown Source:250)
	at LSPHooker_.createOrUpdateClassLoaderLocked(Unknown Source:11)
	at android.app.LoadedApk.getClassLoader(LoadedApk.java:1139)
	at android.app.LoadedApk.getResources(LoadedApk.java:1398)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3100)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3092)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7199)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8503)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: java.lang.ClassNotFoundException: com.android.wm.shell.common.split.SplitUtilsImpl
	... 27 more

**Comment by YifePlayte** [comment]
上下分屏功能不会再维护，因为实现很脏且维护困难，只在个别版本系统下可用。
